before_script:
    - eval $(ssh-agent -s)
variables:
    CI: "false"
stages:
    - build
    - release
contract_build:
    tags:
        - centos7
    stage: build
    script:
        - npm install
        - npm run compile
    only:
        - master
contracts_release:
    tags:
        - centos7
    stage: release
    before_script:
        - npm install gitlab-ci-releaser
    script:
        - npm install
        - npm run compile
        - CI_BUILD_REPO=$CI_REPOSITORY_URL CI_BUILD_REF_NAME=$CI_COMMIT_REF_NAME CI_BUILD_ID=$CI_JOB_ID $(npm bin)/gitlab-ci-releaser
        - npm publish
    when: manual
    only:
        - master
