before_script:
    - eval $(ssh-agent -s)
variables:
    CI: "false"
stages:
    - build
contract_build:
    tags:
        - centos7
    stage: build
    script:
        - npm install
        - npm run compile
    only:
        - master
